I've finished a part of day8.homework
shkadar79/Olga_Maroz_AT_G6_new pull request #3
Opened 2022-10-24 21:36 UTC by shkadar79

2022-10-25 10:29 UTC, ValeryMikulionak requested changes

2022-10-25 10:29 UTC, ValeryMikulionak commented on src/main/java/homework/day8/List/FiguresList.java
> +        List<String> figures = new ArrayList<>();
В этом задании нужно было использовать Arrays.asList()
Конструкция будет:
List<String> figures = new ArrayList<>(Arrays.asList("Овал", "Прямоугольник", "Круг", "Квадрат", "Эллипс"));

2022-10-25 15:52 UTC, ValeryMikulionak requested changes

2022-10-25 15:52 UTC, ValeryMikulionak commented on src/main/java/homework/day8/List/FiguresList.java
> +        out.write(printList.substring(0, printList.length()));
printList.length() - 1 если напишешь то будет печатать без тире на конце

2022-10-25 15:52 UTC, ValeryMikulionak commented on src/main/java/homework/day8/List/CountriesList.java
>              System.out.print(countries.get(i) + " ");
тут надо распечатать с новой строчки, в кавычки добавь \n

2022-10-25 15:52 UTC, ValeryMikulionak commented on src/main/java/homework/day8/List/CountriesList.java
>              System.out.print(i + ", ");
Тут распечатается в конце с запятой, можешь попробовать через билдера сделать как в задании с фигурами

2022-10-25 18:36 UTC, shkadar79 commented on src/main/java/homework/day8/List/FiguresList.java
> +        List<String> figures = new ArrayList<>();
Спасибо, исправила

2022-10-25 18:56 UTC, shkadar79 commented on src/main/java/homework/day8/List/FiguresList.java
> +        out.write(printList.substring(0, printList.length()));
сделала, спасибо

2022-10-25 19:21 UTC, shkadar79 commented on src/main/java/homework/day8/List/CountriesList.java
>              System.out.print(countries.get(i) + " ");
сделала через println

2022-10-26 08:40 UTC, ValeryMikulionak reviewed
All is ok

2022-10-26 08:47 UTC, ValeryMikulionak approved these changes

2022-10-26 12:39 UTC, ValeryMikulionak approved these changes

2022-10-26 12:56 UTC, ValeryMikulionak approved these changes

2022-10-26 13:45 UTC, ValeryMikulionak requested changes

2022-10-26 13:45 UTC, ValeryMikulionak commented on src/main/java/homework/day8/List/NumbersList.java
> +            Collections.sort(numbers, Collections.reverseOrder());
Все работает, но можно было более простой конструкцией сделать: Collections.reverse(numbers);

2022-10-26 13:45 UTC, ValeryMikulionak commented on src/main/java/homework/day8/List/DoublesList.java
> +
еще необходимо доделать:
найти сумму всех дробных частей и вывести результат в консоль
Проитерировать список по индексу и вывести целые части в консоль через пробел

2022-10-27 14:31 UTC, ValeryMikulionak requested changes

2022-10-27 14:31 UTC, ValeryMikulionak commented on src/main/java/homework/day8/List/NumbersList.java
>              System.out.print(i + " ");
тут вроде бы нужно было числа с новой строки выводить

2022-10-27 14:31 UTC, ValeryMikulionak commented on src/main/java/homework/day8/List/NoodlesList.java
> +            System.out.print(i + "-");
тут можешь попробовать тоже через StringBuilder чтоб без тире на конце вывело

2022-10-27 14:31 UTC, ValeryMikulionak commented on src/main/java/homework/day8/List/NoodlesList.java
> +        for (int i = 0; i<noodles.size(); i++) {
Тут нужно было сначала заменить отдельным действием через set, а потом уже вывести отдельным циклов

2022-10-27 14:31 UTC, ValeryMikulionak commented on src/main/java/homework/day8/List/ChairsList.java
> +            counter = i.getHeight() * i.getWidth();
тут можно было без каунтера. просто то чему равен каунтер - записать в скобки для печати.
и ещё лучше добавить один println после первого вывода, а то выводит второй вывод на ту же строчку что и первый.

2022-10-27 18:31 UTC, shkadar79 commented on src/main/java/homework/day8/List/NumbersList.java
> +            Collections.sort(numbers, Collections.reverseOrder());
Спасибо, попробую

2022-10-27 18:31 UTC, shkadar79 commented on src/main/java/homework/day8/List/DoublesList.java
> +
доделала это задание

2022-10-27 18:52 UTC, shkadar79 commented on src/main/java/homework/day8/List/NumbersList.java
>              System.out.print(i + " ");
поправила

2022-10-27 19:12 UTC, shkadar79 commented on src/main/java/homework/day8/List/NoodlesList.java
> +            System.out.print(i + "-");
Поправила

2022-10-27 19:19 UTC, shkadar79 commented on src/main/java/homework/day8/List/NoodlesList.java
> +        for (int i = 0; i<noodles.size(); i++) {
Поправила

2022-10-27 19:24 UTC, shkadar79 commented on src/main/java/homework/day8/List/ChairsList.java
> +            counter = i.getHeight() * i.getWidth();
Поправила

2022-10-28 08:29 UTC, ValeryMikulionak approved these changes

2022-10-28 12:21 UTC, merged